# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-10 01:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('F_USER', models.CharField(max_length=50)),
                ('F_PWD', models.CharField(max_length=50)),
            ],
        ),
    ]
